version: '3.8'

services:
  db:
    image: postgres:11
    #env_file:
    #  - '.env'
    environment:
      POSTGRES_USER: turtle
      POSTGRES_PASSWORD: TeicMav0
      POSTGRES_DB: cloud
    ports:
      - 5432:5432
    volumes:
      - ../../postgres-data:/var/lib/postgresql/data/

  server:
    build:
      context:  ../
      dockerfile: Dockerfile
    command: lapis server
    volumes:
      - ../:/app
      - ../:/app/static/beta:ro
    ports:
      - "8000:8000"
    depends_on:
      - db
